name: Generate sitemap 

on:
  push:
    branches: [ main ]
    paths: [ '**.html', '**.pdf' ]

jobs:
  sitemap_job:
    runs-on: ubuntu-latest
    name: Generate a sitemap
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 
    
    - name: Generate the sitemap
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://harryrobson.com/
    
    - name: Output stats
      run: |
        echo "sitemap-path = ${{ steps.sitemap.outputs.sitemap-path }}"
        echo "url-count = ${{ steps.sitemap.outputs.url-count }}"
        echo "excluded-count = ${{ steps.sitemap.outputs.excluded-count }}"
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4.2.3
      with:
        title: "Automated sitemap update"
        body: > 
          Automated sitemap update
        commit-message: "Automated sitemap update."
        author: Harry Robson <107935327+Harry-Robson@users.noreply.github.com>
        committer: Harry Robson <107935327+Harry-Robson@users.noreply.github.com>
        branch: create-pull-request/sitemap
        delete-branch: true
